select * from customer ;

SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer';


-- 1. Top-Selling Categories

select category , 
		count (*) as total_sales ,
		sum ( purchase_amount) as total_revenue
from customer  
group by category 
order by total_revenue desc;


-- 2. Customer Segmentation by Age Group

select age_group , 
		count (*) as customer_amount ,
		sum ( purchase_amount) as total_revenue 
from customer 
group by age_group 
order by total_revenue desc; 

-- 3. Churn Risk Detection (No Subscription)

select count(*)  as potential_customers
from customer
where subscription_status = 'No';

-- 4. Average Purchase Frequency by Segment

select age_group , 
		count (*) as customer_amount ,
		avg ( purchase_amount) as Average_Purchase_Frequency_by_Segment
from customer 
group by age_group 
order by Average_Purchase_Frequency_by_Segment desc; 
		
-- 5. Top Locations by Revenue

select location , 
		count (*) as customer_amount ,
		sum ( purchase_amount) as total_revenue 
from customer 
group by location 
order by total_revenue desc
limit 10 ;

-- 6. Product Preferences by Gender

select gender , 
		category, 
		count (*) as customer_amount ,
		sum ( purchase_amount) as total_revenue 
from customer 
group by gender , category 
order by  gender ,  total_revenue desc;

-- 7. Shipping Type Impact on Revenue

select shipping_type , 
		category, 
		count (*) as customer_amount ,
		sum ( purchase_amount) as total_revenue 
from customer 
group by shipping_type , category 
order by  shipping_type ,  total_revenue desc ;

-- 8 Discount Effectiveness

select discount_applied ,
		count (*) as orders ,
		sum ( purchase_amount) as total_revenue  
from customer 
group by discount_applied 
order by total_revenue ;


-- 9. High-Value Customers (Top 10%)

select * from customer 
order by purchase_amount desc 
limit (
		select count (*) * 0.1 from customer 
);

-- 10. Review Rating vs Purchase Amount

select  customer_id , 
		round (review_rating::numeric, 1) AS rating,
       count (*) as reviews,
      round (avg (purchase_amount), 2) as avg_spend
from customer
group by ROUND(review_rating::numeric, 1) ,customer_id
order by  rating desc;

-- 11. Customer Lifetime Value Estimation

select customer_id , 
		sum (purchase_amount) as total_spent, 
		round (avg (purchase_amount), 1) as average_order_valure 
from customer 
group by customer_id 
order by total_spent 
limit 10 ;

--  12. Most Popular Items by Season

select season ,
		item_purchased ,
		count (*) as total_order ,
		sum (purchase_amount) as total_order_value 
from customer 
group by season , item_purchased 
order by season , total_order desc ;



-- 13. Payment Method Preferences by Age Group

select age_group ,
		payment_method , 
		count (*) as total_order 
from customer 
group by age_group ,payment_method 
order by age_group , total_order desc ; 


-- ['customer_id', 'age', 'gender', 'item_purchased', 'category',
  --     'purchase_amount', 'location', 'size', 'color', 'season',
    --   'review_rating', 'subscription_status', 'shipping_type',
      -- 'discount_applied', 'promo_code_used', 'previous_purchases',
      -- 'payment_method', 'frequency_of_purchases', 'age_group',
      -- 'purchase_frequency_days']

-- 14. Repeat Purchase Behavior

select  customer_id ,
		previous_purchases , 
		count (*) as customer_count 
from customer 
group by previous_purchases ,customer_id 
order by customer_count desc ; 

-- 15. Subscription Status vs Purchase Frequency

select  
		subscription_status,
       count (*) as Total_subscription,
      round (avg (purchase_amount), 2) as avg_spend
from customer
group by subscription_status 
order by  avg_spend desc;

-- 16. Subscription Status vs Purchase Frequency

select  
		subscription_status,
		purchase_frequency_days ,
       count (*) as Toral_order ,
      round (avg (purchase_amount), 2) as avg_spend
from customer
group by subscription_status ,purchase_frequency_days
order by subscription_status , avg_spend desc;

-- 17 . Color Preferences by Gender

select color , 
		gender ,
		count (*) as total_order 
from customer 
group by color , gender 
order by gender , total_order desc ; 


-- 18. Shipping Type vs Customer Satisfaction

select shipping_type , 
		round (avg (review_rating::numeric ),2 ) as average_review_rating ,  
		count (*) as total_order 
from customer 
group by shipping_type 
order by average_review_rating desc ;
		
-- 18. High-Spending Customers Without Discounts

select customer_id ,
		purchase_amount  
from customer 
where discount_applied = 'No'
order by purchase_amount desc ;


-- 19 . What is the total revenue generated by male vs. female customers?

select gender ,
		sum (purchase_amount) as total_revenue
from customer 
group by gender 
order by total_revenue ;

--20 .  Which customers used a discount but still spent more than the average purchase amount? 

select customer_id , 
		sum (purchase_amount) as total_revenue 
from customer 

where discount_applied = 'Yes' and purchase_amount > (select avg (purchase_amount) from customer )
group by customer_id 
order by customer_id ;


-- 21. Which are the top 5 products with the highest average review rating?

select item_purchased , 
		round (avg (review_rating::numeric ),2 ) as average_review_rating 
from customer 
group by item_purchased 
order by average_review_rating ;

--22. Compare the average Purchase Amounts between Standard and Express Shipping. 

select round (avg (purchase_amount), 2) as average_Purchase_Amount,
		shipping_type 
from customer 
where shipping_type in ('Standard' , 'Express')
group by shipping_type 
order by average_Purchase_Amount desc ;


--23. Do subscribed customers spend more? Compare average spend and total revenue  between subscribers and non-subscribers.

select subscription_status , 
		round (avg (purchase_amount), 2) as average_Purchase_Amount ,
		round (sum (purchase_amount), 2) as total_revenue 
from customer 
group by subscription_status ;

--24. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased , 
		round (100.0 * sum (case 
								when discount_applied = 'Yes' then 1 
								else 0 end )
							/ count (*),2 ) as discount_rate 
from customer 
group by item_purchased 
order by discount_rate desc 
limit 5 ;


--25. Segment customers into New, Returning, and Loyal based on their total  number of previous purchases, and show the count of each segment. 

with customer_type as (

						select customer_id , 
						previous_purchases ,
						case 
								when previous_purchases = 1 then 'New'
								when  previous_purchases between 2 and 10 then 'Returning'
								else 'Loyal'
								end 
							 as customer_segment
						from  customer 

) 

select customer_segment ,
		count (*) as total_customer 
from customer_type 
group by customer_segment 
order by total_customer desc ;


-- 26 What are the top 3 most purchased products within each category? 

with ranked as (

				select item_purchased ,
				
				category ,
				count (*) as purchase_count ,
				rank () over (partition by category order by count (*) desc ) as rank 
from customer 
group by  item_purchased ,category

)

select category , 
		item_purchased
		
from ranked 
where rank <= 3 
order by category , purchase_count desc ;

--27. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status , 
		count (*) as repeted_buyers 
from customer 
where previous_purchases > 5 
group by subscription_status 
order by subscription_status desc ;


--28. What is the revenue contribution of each age group? 


select age_group ,
		round (sum (purchase_amount), 2) as total_revenue  

from customer 
group by age_group 
order by total_revenue desc ;











